spring:
  datasource:
    url: jdbc:h2:mem:testdb
    driver-class-name: org.h2.Driver
    username: sa
    password:
  h2:
    console:
      enabled: true
#  aop:
#    auto: true
#    proxy-target-class: true


  jpa:
    hibernate:
      ddl-auto=update: update
  sql:
    init:
      mode: embedded

server:
  port: 8080
  servlet:
    context-path: /taleb

springdoc:
  api-docs:
    enabled: true
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html
    enabled: true